#!/bin/sh
set -eu

export GF_SECURITY_ADMIN_USER="${SERVICE_USER_GRAFANA_ADMIN:?SERVICE_USER_GRAFANA_ADMIN is required}"
export GF_SECURITY_ADMIN_PASSWORD="${SERVICE_PASSWORD_GRAFANA_ADMIN:?SERVICE_PASSWORD_GRAFANA_ADMIN is required}"

exec /run.sh "$@"
