#!/bin/sh
set -eu

export POSTGRES_USER="${SERVICE_USER_POSTGRES:?SERVICE_USER_POSTGRES is required}"
export POSTGRES_PASSWORD="${SERVICE_PASSWORD_POSTGRES:?SERVICE_PASSWORD_POSTGRES is required}"
export GRAFANA_DB_USER="${SERVICE_USER_GRAFANA_DB:?SERVICE_USER_GRAFANA_DB is required}"
export GRAFANA_DB_PASSWORD="${SERVICE_PASSWORD_GRAFANA_DB:?SERVICE_PASSWORD_GRAFANA_DB is required}"

exec docker-entrypoint.sh "$@"
