from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    LargeBinary,
    MetaData,
    SmallInteger,
    String,
    Table,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects import postgresql


metadata = MetaData()

collector_senders = Table(
    "collector_senders",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("device_id", Text, nullable=False, unique=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
    Column("notes", Text),
)

ingest_batches = Table(
    "ingest_batches",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("sender_id", ForeignKey("collector_senders.id")),
    Column("received_at", DateTime(timezone=True), nullable=False),
    Column("client_host", postgresql.INET),
    Column("body_len", Integer, nullable=False),
    Column("body_sha256", LargeBinary, nullable=False),
    Column("content_type", Text),
    Column("batch_seq", BigInteger),
    Column("declared_record_count", Integer),
    Column("parsed_record_count", Integer),
    Column("payload_len", BigInteger),
    Column("sender_uptime_ms", BigInteger),
    Column("parse_ok", Boolean, nullable=False),
    Column("parse_error", Text),
    Column("sender_status", postgresql.JSONB),
    Column("raw_body", LargeBinary),
    Index("ingest_batches_received_at_idx", "received_at"),
    Index(
        "ingest_batches_sender_seq_idx",
        "sender_id",
        "batch_seq",
        unique=True,
        postgresql_where=Column("parse_ok").is_(True),
    ),
)

mac_addresses = Table(
    "mac_addresses",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("mac_hash", LargeBinary, nullable=False, unique=True),
    Column("mac_text", Text),
    Column("oui", LargeBinary),
    Column("is_local_admin", Boolean, nullable=False),
    Column("is_multicast", Boolean, nullable=False),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
)

sniffer_clock_state = Table(
    "sniffer_clock_state",
    metadata,
    Column("sender_id", ForeignKey("collector_senders.id"), primary_key=True),
    Column("source_id", Integer, primary_key=True),
    Column("last_rx_ts_us_32", BigInteger, nullable=False),
    Column("wrap_count", BigInteger, nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

wifi_frames = Table(
    "wifi_frames",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("batch_id", ForeignKey("ingest_batches.id"), nullable=False),
    Column("record_index", Integer, nullable=False),
    Column("sender_id", ForeignKey("collector_senders.id"), nullable=False),
    Column("source_id", Integer, nullable=False),
    Column("received_at", DateTime(timezone=True), nullable=False),
    Column("observed_at", DateTime(timezone=True)),
    Column("sender_uptime_ms", BigInteger),
    Column("rx_ts_us_32", BigInteger, nullable=False),
    Column("rx_ts_us_unwrapped", BigInteger),
    Column("snif_seq", BigInteger, nullable=False),
    Column("channel", SmallInteger, nullable=False),
    Column("rssi", SmallInteger, nullable=False),
    Column("frame_len", Integer, nullable=False),
    Column("truncated", Boolean, nullable=False),
    Column("crc16", Integer, nullable=False),
    Column("frame_control", Integer),
    Column("mgmt_subtype", SmallInteger),
    Column("mgmt_subtype_name", Text),
    Column("duration_id", Integer),
    Column("seq_num", Integer),
    Column("frag_num", Integer),
    Column("retry", Boolean),
    Column("protected", Boolean),
    Column("addr1_id", ForeignKey("mac_addresses.id")),
    Column("addr2_id", ForeignKey("mac_addresses.id")),
    Column("addr3_id", ForeignKey("mac_addresses.id")),
    Column("station_mac_id", ForeignKey("mac_addresses.id")),
    Column("ap_mac_id", ForeignKey("mac_addresses.id")),
    Column("ssid_hash", LargeBinary),
    Column("ssid_text", Text),
    Column("ssid_len", SmallInteger),
    Column("ssid_is_wildcard", Boolean),
    Column("ie_ids", postgresql.ARRAY(SmallInteger)),
    Column("vendor_ouis", postgresql.JSONB),
    Column("fixed_fields", postgresql.JSONB),
    Column("parse_ok", Boolean, nullable=False),
    Column("parse_error", Text),
    Column("is_station_originated", Boolean),
    Column("direction", Text, nullable=False, default="unknown"),
    Column("direction_confidence", SmallInteger, nullable=False, default=0),
    Column("direction_reason", Text),
    Column("src_is_randomized", Boolean),
    Column("burst_id", ForeignKey("station_bursts.id")),
    UniqueConstraint("batch_id", "record_index", name="wifi_frames_batch_record_uniq"),
    Index("wifi_frames_received_at_idx", "received_at"),
    Index("wifi_frames_observed_at_idx", "observed_at"),
    Index("wifi_frames_sender_source_rx_idx", "sender_id", "source_id", "rx_ts_us_unwrapped"),
    Index("wifi_frames_subtype_time_idx", "mgmt_subtype", "observed_at"),
    Index("wifi_frames_addr2_rx_idx", "addr2_id", "rx_ts_us_unwrapped"),
    Index(
        "wifi_frames_station_rx_idx",
        "station_mac_id",
        "rx_ts_us_unwrapped",
        postgresql_where=Column("is_station_originated").is_(True),
    ),
    Index("wifi_frames_ie_ids_gin_idx", "ie_ids", postgresql_using="gin"),
)

wifi_frame_payloads = Table(
    "wifi_frame_payloads",
    metadata,
    Column("frame_id", ForeignKey("wifi_frames.id", ondelete="CASCADE"), primary_key=True),
    Column("raw_frame", LargeBinary, nullable=False),
    Column("raw_frame_sha256", LargeBinary, nullable=False),
)

access_points = Table(
    "access_points",
    metadata,
    Column("mac_id", ForeignKey("mac_addresses.id"), primary_key=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
    Column("channels", postgresql.ARRAY(SmallInteger), nullable=False),
    Column("ssid_hashes", postgresql.ARRAY(LargeBinary), nullable=False),
    Column("beacon_count", BigInteger, nullable=False, default=0),
    Column("probe_response_count", BigInteger, nullable=False, default=0),
    Column("assoc_response_count", BigInteger, nullable=False, default=0),
    Column("evidence_score", Integer, nullable=False, default=0),
)

station_bursts = Table(
    "station_bursts",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("station_mac_id", ForeignKey("mac_addresses.id"), nullable=False),
    Column("source_id", Integer),
    Column("started_rx_ts_us", BigInteger, nullable=False),
    Column("ended_rx_ts_us", BigInteger, nullable=False),
    Column("started_at", DateTime(timezone=True)),
    Column("ended_at", DateTime(timezone=True)),
    Column("frame_count", Integer, nullable=False),
    Column("probe_only", Boolean, nullable=False),
    Column("full_management", Boolean, nullable=False),
    Column("randomized_mac", Boolean),
    Column("build_version", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("station_bursts_station_time_idx", "station_mac_id", "started_rx_ts_us"),
)

burst_fsm_features = Table(
    "burst_fsm_features",
    metadata,
    Column("burst_id", ForeignKey("station_bursts.id", ondelete="CASCADE"), primary_key=True),
    Column("feature_version", Integer, nullable=False),
    Column("subtype_counts", postgresql.JSONB, nullable=False),
    Column("transition_counts", postgresql.JSONB, nullable=False),
    Column("transition_entropy", postgresql.DOUBLE_PRECISION),
    Column("unique_state_count", Integer, nullable=False),
    Column("total_transition_count", Integer, nullable=False),
    Column("self_transition_count", Integer, nullable=False),
    Column("transition_rate_hz", postgresql.DOUBLE_PRECISION),
    Column("mean_inter_frame_gap_ms", postgresql.DOUBLE_PRECISION),
    Column("p50_inter_frame_gap_ms", postgresql.DOUBLE_PRECISION),
    Column("p90_inter_frame_gap_ms", postgresql.DOUBLE_PRECISION),
    Column("max_seq_gap", Integer),
    Column("ie_bitset", LargeBinary),
    Column("ie_ids", postgresql.ARRAY(SmallInteger)),
    Column("channel_sequence", postgresql.ARRAY(SmallInteger)),
    Column("rssi_mean", postgresql.DOUBLE_PRECISION),
    Column("rssi_stddev", postgresql.DOUBLE_PRECISION),
    Column("feature_vector", postgresql.JSONB, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

device_link_scores = Table(
    "device_link_scores",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("left_burst_id", ForeignKey("station_bursts.id"), nullable=False),
    Column("right_burst_id", ForeignKey("station_bursts.id"), nullable=False),
    Column("model_version", Text, nullable=False),
    Column("feature_version", Integer, nullable=False),
    Column("score", postgresql.DOUBLE_PRECISION, nullable=False),
    Column("predicted_same_device", Boolean, nullable=False),
    Column("window_seconds", Integer),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "left_burst_id",
        "right_burst_id",
        "model_version",
        name="device_link_scores_pair_model_uniq",
    ),
)
